In [1]:
import numpy as np

In [3]:
numbers = [10, 20, 30, 40]
arr = np.array(numbers)

print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [4]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(4,)
4
int64


In [5]:
print(arr[0])
print(arr[1])
print(arr[-1])

10
20
40


In [6]:
print(arr[1:4])
print(arr[:3])
print(arr[2:])

[20 30 40]
[10 20 30]
[30 40]


In [9]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
])

print(matrix.ndim)
print(matrix.shape)
print(matrix.size)

2
(3, 3)
9


In [10]:
print(matrix[0])
print(matrix[0, 1])
print(matrix[2, 2])

[10 20 30]
20
90


In [13]:
arr = np.array([10, 20, 30, 40])

print(arr + 5)
print(arr * 2)
print(arr / 10)

[15 25 35 45]
[20 40 60 80]
[1. 2. 3. 4.]


In [14]:
prices = np.array([25, 40, 15, 60, 30])

print(prices.sum())
print(prices.min())
print(prices.max())
print(prices.mean())

170
15
60
34.0


In [15]:
arr = np.array([10, 20, 30, 40])
print(arr > 20)

[False False  True  True]


In [18]:
print(arr[arr > 20])

[30 40]


In [24]:
delivery_days = np.array([2, 5, 1, 8, 4, 10, 3, 6])
print(delivery_days.shape)
print(delivery_days.size)
print(delivery_days.min())
print(delivery_days.max())
print(delivery_days.mean())
print(delivery_days[2])
print(delivery_days[:4])
print(delivery_days[delivery_days > 5])

(8,)
8
1
10
4.875
1
[2 5 1 8]
[ 8 10  6]
